# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ario-grafana" = {
    image = "grafana/grafana:latest";
    environment = {
      "GF_INSTALL_PLUGINS" = "grafana-clock-panel,grafana-polystat-panel";
      "GF_SERVER_HTTP_PORT" = "1024";
      "GF_SERVER_ROOT_URL" = "http://localhost:1024/grafana";
      "GF_SERVER_SERVE_FROM_SUB_PATH" = "true";
      "TERM" = "linux";
    };
    volumes = [
      "/opt/ario/data/grafana:/var/lib/grafana:rw"
      "/opt/ario/monitoring/grafana/dashboards:/etc/grafana/dashboards:rw"
      "/opt/ario/monitoring/grafana/provisioning:/etc/grafana/provisioning:rw"
    ];
    ports = [
      "1024:1024/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=grafana"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ario-grafana" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ario-root.target"
    ];
    wantedBy = [
      "docker-compose-ario-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ario-node-exporter" = {
    image = "prom/node-exporter:v1.3.1";
    volumes = [
      "/:/host:ro"
    ];
    ports = [
      "9100:9100/tcp"
    ];
    cmd = [ "--path.rootfs=/host" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=node-exporter"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ario-node-exporter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ario-root.target"
    ];
    wantedBy = [
      "docker-compose-ario-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ario-prometheus" = {
    image = "prom/prometheus:latest";
    volumes = [
      "/opt/ario/prometheus.yml:/etc/prometheus/prometheus.yml:rw"
    ];
    ports = [
      "9090:9090/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prometheus"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ario-prometheus" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ario-root.target"
    ];
    wantedBy = [
      "docker-compose-ario-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ario-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
