# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ar-io-node-autoheal" = {
    image = "willfarrell/autoheal@sha256:fd2c5500ab9210be9fa0d365162301eb0d16923f1d9a36de887f5d1751c6eb8c";
    environment = {
      "AUTOHEAL_CONTAINER_LABEL" = "autoheal";
      "AUTOHEAL_ONLY_MONITOR_RUNNING" = "false";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=none"
    ];
  };
  systemd.services."docker-ar-io-node-autoheal" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ar-io-node-root.target"
    ];
    wantedBy = [
      "docker-compose-ar-io-node-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ar-io-node-core" = {
    image = "ghcr.io/ar-io/ar-io-core:ac6dc46881a29cd1d39ab0466e2bf219dc2a363c";
    environment = {
      "ADMIN_API_KEY" = "";
      "ANS104_DOWNLOAD_WORKERS" = "";
      "ANS104_INDEX_FILTER" = "";
      "ANS104_UNBUNDLE_FILTER" = "";
      "ANS104_UNBUNDLE_WORKERS" = "";
      "ANT_AO_CU_URL" = "";
      "AO_ANT_HYPERBEAM_URL" = "";
      "AO_CU_URL" = "";
      "AO_GATEWAY_URL" = "";
      "AO_GRAPHQL_URL" = "";
      "AO_MU_URL" = "";
      "APEX_ARNS_NAME" = "";
      "APEX_TX_ID" = "";
      "ARIO_PROCESS_DEFAULT_CIRCUIT_BREAKER_ERROR_THRESHOLD_PERCENTAGE" = "";
      "ARIO_PROCESS_DEFAULT_CIRCUIT_BREAKER_RESET_TIMEOUT_MS" = "";
      "ARIO_PROCESS_DEFAULT_CIRCUIT_BREAKER_ROLLING_COUNT_TIMEOUT_MS" = "";
      "ARIO_PROCESS_DEFAULT_CIRCUIT_BREAKER_TIMEOUT_MS" = "";
      "ARNS_CACHE_MAX_KEYS" = "10000";
      "ARNS_CACHE_TTL_SECONDS" = "";
      "ARNS_CACHE_TYPE" = "redis";
      "ARNS_COMPOSITE_RESOLVER_TIMEOUT_MS" = "";
      "ARNS_MAX_CONCURRENT_RESOLUTIONS" = "";
      "ARNS_NAMES_CACHE_TTL_SECONDS" = "";
      "ARNS_NOT_FOUND_ARNS_NAME" = "";
      "ARNS_NOT_FOUND_TX_ID" = "";
      "ARNS_RESOLVER_ENFORCE_UNDERNAME_LIMIT" = "";
      "ARNS_RESOLVER_OVERRIDE_TTL_SECONDS" = "";
      "ARNS_RESOLVER_PRIORITY_ORDER" = "";
      "ARNS_ROOT_HOST" = "permaframes.cc";
      "ARWEAVE_NODE_IGNORE_URLS" = "";
      "ARWEAVE_POST_DRY_RUN" = "false";
      "ARWEAVE_POST_DRY_RUN_SKIP_VALIDATION" = "false";
      "AR_IO_NODE_RELEASE" = "64";
      "AR_IO_SDK_LOG_LEVEL" = "none";
      "AR_IO_WALLET" = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
      "AWS_ACCESS_KEY_ID" = "";
      "AWS_DYNAMODB_TURBO_ASSUME_ROLE_ARN" = "";
      "AWS_DYNAMODB_TURBO_DATA_ITEM_TABLE" = "";
      "AWS_DYNAMODB_TURBO_ENDPOINT" = "";
      "AWS_DYNAMODB_TURBO_OFFSETS_TABLE" = "";
      "AWS_DYNAMODB_TURBO_REGION" = "";
      "AWS_ELASTICACHE_TURBO_HOST" = "";
      "AWS_ELASTICACHE_TURBO_PORT" = "";
      "AWS_ELASTICACHE_TURBO_USE_TLS" = "";
      "AWS_ENDPOINT" = "";
      "AWS_REGION" = "";
      "AWS_S3_CONTIGUOUS_DATA_BUCKET" = "";
      "AWS_S3_CONTIGUOUS_DATA_PREFIX" = "";
      "AWS_SECRET_ACCESS_KEY" = "";
      "BACKFILL_BUNDLE_RECORDS" = "";
      "BACKGROUND_DATA_VERIFICATION_INTERVAL_SECONDS" = "";
      "BACKGROUND_RETRIEVAL_ORDER" = "";
      "BUNDLER_URLS" = "";
      "BUNDLE_DATA_IMPORTER_QUEUE_SIZE" = "";
      "BUNDLE_REPAIR_BACKFILL_INTERVAL_SECONDS" = "";
      "BUNDLE_REPAIR_FILTER_REPROCESS_INTERVAL_SECONDS" = "";
      "BUNDLE_REPAIR_RETRY_BATCH_SIZE" = "";
      "BUNDLE_REPAIR_RETRY_INTERVAL_SECONDS" = "";
      "BUNDLE_REPAIR_UPDATE_TIMESTAMPS_INTERVAL_SECONDS" = "";
      "CDB64_ROOT_TX_INDEX_WATCH" = "";
      "CDP_API_KEY_ID" = "";
      "CDP_API_KEY_SECRET" = "";
      "CDP_API_KEY_SECRET_FILE" = "";
      "CHAIN_CACHE_TYPE" = "redis";
      "CHUNK_DATA_RETRIEVAL_ORDER" = "";
      "CHUNK_DATA_SOURCE_PARALLELISM" = "";
      "CHUNK_METADATA_CACHE_TYPE" = "redis";
      "CHUNK_METADATA_RETRIEVAL_ORDER" = "";
      "CHUNK_METADATA_SOURCE_PARALLELISM" = "";
      "CHUNK_OFFSET_CHAIN_FALLBACK_CONCURRENCY" = "";
      "CHUNK_POST_ABORT_TIMEOUT_MS" = "";
      "CHUNK_POST_MIN_SUCCESS_COUNT" = "";
      "CHUNK_POST_PEER_CONCURRENCY" = "";
      "CHUNK_POST_PER_NODE_CONCURRENCY" = "";
      "CHUNK_POST_QUEUE_DEPTH_THRESHOLD" = "";
      "CHUNK_POST_RESPONSE_TIMEOUT_MS" = "";
      "CHUNK_POST_SORTED_PEERS_CACHE_DURATION_MS" = "";
      "CHUNK_REBROADCAST_DEDUP_TTL_SECONDS" = "";
      "CHUNK_REBROADCAST_MAX_CONCURRENT" = "";
      "CHUNK_REBROADCAST_MIN_SUCCESS_COUNT" = "";
      "CHUNK_REBROADCAST_RATE_LIMIT_INTERVAL" = "";
      "CHUNK_REBROADCAST_RATE_LIMIT_TOKENS" = "";
      "CHUNK_REBROADCAST_SOURCES" = "";
      "CHUNK_SYMLINK_CLEANUP_INTERVAL" = "";
      "CLICKHOUSE_PASSWORD" = "";
      "CLICKHOUSE_URL" = "";
      "CLICKHOUSE_USER" = "";
      "CONTIGUOUS_DATA_CACHE_CLEANUP_THRESHOLD" = "86400";
      "DATA_ITEM_FLUSH_COUNT_THRESHOLD" = "";
      "ENABLE_BACKGROUND_DATA_VERIFICATION" = "";
      "ENABLE_CHUNK_SYMLINK_CLEANUP" = "";
      "ENABLE_DATASETS_ENDPOINT" = "";
      "ENABLE_DATA_DB_WAL_CLEANUP" = "";
      "ENABLE_DATA_ITEM_ROOT_TX_SEARCH" = "";
      "ENABLE_FS_HEADER_CACHE_CLEANUP" = "";
      "ENABLE_MEMPOOL_WATCHER" = "";
      "ENABLE_PASSTHROUGH_WITHOUT_OFFSETS" = "";
      "ENABLE_RATE_LIMITER" = "";
      "ENABLE_X_402_USDC_DATA_EGRESS" = "";
      "FILTER_CHANGE_REPROCESS" = "";
      "FS_CLEANUP_WORKER_BATCH_PAUSE_DURATION" = "";
      "FS_CLEANUP_WORKER_BATCH_SIZE" = "";
      "FS_CLEANUP_WORKER_RESTART_PAUSE_DURATION" = "";
      "GATEWAY_PEERS_REQUEST_WINDOW_COUNT" = "";
      "GATEWAY_PEERS_WEIGHTS_CACHE_DURATION_MS" = "";
      "INSTANCE_ID" = "";
      "IO_PROCESS_ID" = "";
      "LEGACY_AWS_S3_ACCESS_KEY_ID" = "";
      "LEGACY_AWS_S3_CHUNK_DATA_BUCKET" = "";
      "LEGACY_AWS_S3_CHUNK_DATA_PREFIX" = "";
      "LEGACY_AWS_S3_ENDPOINT" = "";
      "LEGACY_AWS_S3_REGION" = "";
      "LEGACY_AWS_S3_SECRET_ACCESS_KEY" = "";
      "LEGACY_PSQL_CONNECTION_STRING" = "";
      "LEGACY_PSQL_CONNECT_TIMEOUT_SECONDS" = "";
      "LEGACY_PSQL_IDLE_IN_TRANSACTION_TIMEOUT_MS" = "";
      "LEGACY_PSQL_IDLE_TIMEOUT_SECONDS" = "";
      "LEGACY_PSQL_MAX_CONNECTIONS" = "";
      "LEGACY_PSQL_MAX_LIFETIME_SECONDS" = "";
      "LEGACY_PSQL_PASSWORD_FILE" = "";
      "LEGACY_PSQL_SSL_REJECT_UNAUTHORIZED" = "";
      "LEGACY_PSQL_STATEMENT_TIMEOUT_MS" = "";
      "LOG_FILTER" = "";
      "LOG_FORMAT" = "simple";
      "LOG_LEVEL" = "info";
      "MAX_DATA_ITEM_QUEUE_SIZE" = "";
      "MAX_EXPECTED_DATA_ITEM_INDEXING_INTERVAL_SECONDS" = "";
      "MAX_FLUSH_INTERVAL_SECONDS" = "";
      "MEMPOOL_POOLING_INTERVAL_MS" = "";
      "MIN_DATA_VERIFICATION_PRIORITY" = "";
      "NETWORK_AO_CU_URL" = "";
      "NODE_ENV" = "production";
      "NODE_MAX_OLD_SPACE_SIZE" = "";
      "ON_DEMAND_RETRIEVAL_ORDER" = "";
      "OTEL_BATCH_LOG_PROCESSOR_MAX_EXPORT_BATCH_SIZE" = "";
      "OTEL_BATCH_LOG_PROCESSOR_SCHEDULED_DELAY_MS" = "";
      "OTEL_EXPORTER_OTLP_ENDPOINT" = "";
      "OTEL_EXPORTER_OTLP_HEADERS" = "";
      "OTEL_EXPORTER_OTLP_HEADERS_FILE" = "";
      "OTEL_SERVICE_NAME" = "";
      "OTEL_TRACING_SAMPLING_RATE_DENOMINATOR" = "";
      "PEER_REFRESH_CONCURRENCY" = "";
      "PREFERRED_ARNS_BASE_NAMES" = "";
      "PREFERRED_ARNS_CONTIGUOUS_DATA_CACHE_CLEANUP_THRESHOLD" = "";
      "PREFERRED_ARNS_NAMES" = "";
      "PREFERRED_CHUNK_GET_NODE_URLS" = "";
      "PREFERRED_CHUNK_POST_NODE_URLS" = "";
      "PREFERRED_CHUNK_POST_WEIGHT" = "";
      "RATE_LIMITER_ARNS_ALLOWLIST" = "";
      "RATE_LIMITER_IPS_AND_CIDRS_ALLOWLIST" = "";
      "RATE_LIMITER_IP_REFILL_PER_SEC" = "";
      "RATE_LIMITER_IP_TOKENS_PER_BUCKET" = "";
      "RATE_LIMITER_REDIS_ENDPOINT" = "redis://redis:6379";
      "RATE_LIMITER_REDIS_USE_CLUSTER" = "";
      "RATE_LIMITER_REDIS_USE_TLS" = "";
      "RATE_LIMITER_RESOURCE_REFILL_PER_SEC" = "";
      "RATE_LIMITER_RESOURCE_TOKENS_PER_BUCKET" = "";
      "RATE_LIMITER_TYPE" = "redis";
      "REDIS_CACHE_TTL_SECONDS" = "";
      "REDIS_CACHE_URL" = "redis://redis:6379";
      "REDIS_USE_TLS" = "";
      "ROOT_TX_LOOKUP_ORDER" = "";
      "SANDBOX_PROTOCOL" = "";
      "SIMULATED_REQUEST_FAILURE_RATE" = "";
      "SKIP_CACHE" = "";
      "SKIP_DATA_CACHE" = "";
      "START_HEIGHT" = "";
      "START_WRITERS" = "";
      "STOP_HEIGHT" = "";
      "TAG_SELECTIVITY" = "";
      "TRUSTED_ARNS_GATEWAY_URL" = "";
      "TRUSTED_GATEWAYS_BLOCKED_IPS_AND_CIDRS" = "";
      "TRUSTED_GATEWAYS_BLOCKED_ORIGINS" = "";
      "TRUSTED_GATEWAYS_REQUEST_TIMEOUT_MS" = "";
      "TRUSTED_GATEWAYS_URLS" = "";
      "TRUSTED_GATEWAY_URL" = "";
      "TRUSTED_NODE_URL" = "http://envoy:3000";
      "WEBHOOK_BLOCK_FILTER" = "";
      "WEBHOOK_INDEX_FILTER" = "";
      "WEBHOOK_TARGET_SERVERS" = "";
      "WEIGHTED_PEERS_TEMPERATURE_DELTA" = "";
      "WRITE_ANS104_DATA_ITEM_DB_SIGNATURES" = "";
      "WRITE_TRANSACTION_DB_SIGNATURES" = "";
      "X_402_APP_LOGO" = "";
      "X_402_APP_NAME" = "";
      "X_402_CDP_CLIENT_KEY" = "";
      "X_402_RATE_LIMIT_CAPACITY_MULTIPLIER" = "";
      "X_402_SESSION_TOKEN_ENDPOINT" = "";
      "X_402_USDC_DATA_EGRESS_MAX_PRICE" = "";
      "X_402_USDC_DATA_EGRESS_MIN_PRICE" = "";
      "X_402_USDC_FACILITATOR_URL" = "";
      "X_402_USDC_NETWORK" = "";
      "X_402_USDC_PER_BYTE_PRICE" = "";
      "X_402_USDC_SETTLE_TIMEOUT_MS" = "";
      "X_402_USDC_WALLET_ADDRESS" = "";
    };
    volumes = [
      "/root/data/cdb64-root-tx-index:/app/data/cdb64-root-tx-index:rw"
      "/root/data/chunks:/app/data/chunks:rw"
      "/root/data/contiguous:/app/data/contiguous:rw"
      "/root/data/datasets:/app/data/datasets:rw"
      "/root/data/duckdb:/app/data/duckdb:rw"
      "/root/data/headers:/app/data/headers:rw"
      "/root/data/lmdb:/app/data/lmdb:rw"
      "/root/data/parquet:/app/data/parquet:rw"
      "/root/data/sqlite:/app/data/sqlite:rw"
      "/root/data/tmp:/app/data/tmp:rw"
      "/root/secrets:/app/secrets:ro"
    ];
    ports = [
      "4000:4000/tcp"
    ];
    labels = {
      "autoheal" = "false";
    };
    dependsOn = [
      "ar-io-node-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=core"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ar-io-node-core" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ar-io-network.service"
    ];
    requires = [
      "docker-network-ar-io-network.service"
    ];
    partOf = [
      "docker-compose-ar-io-node-root.target"
    ];
    wantedBy = [
      "docker-compose-ar-io-node-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ar-io-node-envoy" = {
    image = "ghcr.io/ar-io/ar-io-envoy:4755fa0a2deb258bfaeaa91ba3154f1f7ef41fda";
    environment = {
      "LOG_LEVEL" = "info";
      "TVAL_ARNS_ROOT_HOST" = "permaframes.cc";
      "TVAL_ARWEAVE_POST_DRY_RUN" = "false";
      "TVAL_AR_IO_HOST" = "core";
      "TVAL_AR_IO_PORT" = "4000";
      "TVAL_DATASETS_HOST" = "core";
      "TVAL_DATASETS_PORT" = "4000";
      "TVAL_FALLBACK_NODE_HOST" = "peers.arweave.xyz";
      "TVAL_FALLBACK_NODE_PORT" = "1984";
      "TVAL_GRAPHQL_HOST" = "core";
      "TVAL_GRAPHQL_PORT" = "4000";
      "TVAL_OBSERVER_HOST" = "observer";
      "TVAL_OBSERVER_PORT" = "5050";
      "TVAL_TRUSTED_NODE_HOST" = "arweave.net";
      "TVAL_TRUSTED_NODE_PORT" = "443";
    };
    ports = [
      "3000:3000/tcp"
    ];
    dependsOn = [
      "ar-io-node-core"
      "ar-io-node-observer"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=envoy"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ar-io-node-envoy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ar-io-network.service"
    ];
    requires = [
      "docker-network-ar-io-network.service"
    ];
    partOf = [
      "docker-compose-ar-io-node-root.target"
    ];
    wantedBy = [
      "docker-compose-ar-io-node-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ar-io-node-observer" = {
    image = "ghcr.io/ar-io/ar-io-observer:e34a7f01768d505360a4e0877fe40d55230e864a";
    environment = {
      "AO_CU_URL" = "";
      "AO_GATEWAY_URL" = "";
      "AO_GRAPHQL_URL" = "";
      "AO_MU_URL" = "";
      "AR_IO_NODE_RELEASE" = "64";
      "AR_IO_SDK_LOG_LEVEL" = "none";
      "IO_PROCESS_ID" = "";
      "LOG_LEVEL" = "";
      "MIN_RELEASE_NUMBER" = "0";
      "NETWORK_AO_CU_URL" = "";
      "NUM_ARNS_NAMES_TO_OBSERVE_PER_GROUP" = "8";
      "OBSERVER_WALLET" = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
      "REPORT_DATA_SINK" = "";
      "REPORT_GENERATION_INTERVAL_MS" = "";
      "RUN_OBSERVER" = "false";
      "SUBMIT_CONTRACT_INTERACTIONS" = "true";
      "TURBO_UPLOAD_SERVICE_URL" = "";
    };
    volumes = [
      "/root/data/observer:/app/data/observer:rw"
      "/root/data/reports:/app/data/reports:rw"
      "/root/data/tmp:/app/data/tmp:rw"
      "/root/wallets:/app/wallets:rw"
    ];
    ports = [
      "5050:5050/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=observer"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ar-io-node-observer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ar-io-network.service"
    ];
    requires = [
      "docker-network-ar-io-network.service"
    ];
    partOf = [
      "docker-compose-ar-io-node-root.target"
    ];
    wantedBy = [
      "docker-compose-ar-io-node-root.target"
    ];
  };
  virtualisation.oci-containers.containers."ar-io-node-redis" = {
    image = "redis:7";
    volumes = [
      "/root/data/redis:/data:rw"
    ];
    ports = [
      "6379/tcp"
    ];
    cmd = [
      "redis-server"
      "--maxmemory"
      "256mb"
      "--maxmemory-policy"
      "allkeys-lru"
      "--save"
      ""
      "--appendonly"
      "no"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis"
      "--network=ar-io-network"
    ];
  };
  systemd.services."docker-ar-io-node-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ar-io-network.service"
    ];
    requires = [
      "docker-network-ar-io-network.service"
    ];
    partOf = [
      "docker-compose-ar-io-node-root.target"
    ];
    wantedBy = [
      "docker-compose-ar-io-node-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-ar-io-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ar-io-network";
    };
    script = ''
      docker network inspect ar-io-network || docker network create ar-io-network
    '';
    partOf = [ "docker-compose-ar-io-node-root.target" ];
    wantedBy = [ "docker-compose-ar-io-node-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ar-io-node-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
