#!/bin/bash

revision=$1

if [ -z "$revision" ]; then
  echo "Usage: $0 <revision>"
  echo "Example: $0 r64"
  exit 1
fi

if [ ! -d "resources" ]; then
  mkdir resources
fi

rm -f resources/*

gatewayComposeUrl="https://raw.githubusercontent.com/ar-io/ar-io-node/refs/tags/$revision/docker-compose.yaml"

curl -L -o resources/docker-compose.yml "$gatewayComposeUrl"

nix run github:aksiksi/compose2nix -- \
  --project=ario \
  --runtime=docker \
  --root_path=/opt/ario \
  --inputs=resources/docker-compose.yml \
  --output=modules/ario-config.generated.nix

grafanaComposeUrl="https://raw.githubusercontent.com/ar-io/ar-io-node/refs/tags/$revision/docker-compose.grafana.yaml"

curl -L -o resources/docker-compose.grafana.yml "$grafanaComposeUrl"

nix run github:aksiksi/compose2nix -- \
  --project=ario \
  --runtime=docker \
  --root_path=/opt/ario \
  --inputs=resources/docker-compose.grafana.yml \
  --output=modules/grafana-config.generated.nix

prometheusConfigUrl="https://raw.githubusercontent.com/ar-io/ar-io-node/refs/tags/$revision/prometheus.yml"

curl -L -o resources/prometheus.yml "$prometheusConfigUrl"

echo "$revision" > resources/revision 